name: duckOS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-os:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Ubuntu Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential cmake bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo qemu-system-i386 qemu-utils nasm gawk grub2-common grub-pc

      - name: Cache toolchain
        id: cache-toolchain
        uses: actions/cache@v3
        with:
          path: toolchain/tools
          key: ${{ runner.os }}-toolchain-${{ hashFiles('toolchain/*.patch') }}-${{ hashFiles('toolchain/*.sh') }}
      
      - name: Build toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          cd toolchain
          ./build-toolchain.sh
      
      - name: Install headers
        if: steps.cache-toolchain.outputs.cache-hit == 'true'
        run: |
          cd toolchain
          ./build-toolchain.sh install-headers
          ./build-toolchain.sh make-toolchain-file
      
      - name: Build duckOS (Release)
        run: |
          cd build/i686
          cmake ../.. -DCMAKE_TOOLCHAIN_FILE=build/i686/CMakeToolchain.txt -DCMAKE_BUILD_TYPE=Release
          make install
          
      - name: Make image
        run: |
          cd build/i686
          make image
          
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: Disk Image
          path: build/i686/duckOS.img

